name: Waka Readme

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # 基础统计
          SHOW_LINES_OF_CODE: "True"          # 显示代码行数
          SHOW_TOTAL_CODE_TIME: "True"        # 显示总编码时间
          SHOW_TIMEZONE: "false"      # 隐藏时区信息
          HIDE_PROJECTS_WITHOUT_ACTIVITIES: "true"
          
          # 时间相关
          SHOW_DAYS_OF_WEEK: "True"          # 显示每周工作日数据
          SHOW_UPDATED_DATE: "True"          # 显示更新日期
          
          # 编码环境
          SHOW_PROJECTS: "True"              # 显示项目信息
          SHOW_LANGUAGE: "True"              # 显示编程语言
          SHOW_EDITORS: "false"
          SHOW_OS: "false"
          
          # 提交信息
          SHOW_COMMIT: "True"                # 显示提交信息
          SHOW_SHORT_INFO: "True"            # 显示简短信息
          COMMIT_BY_ME: "True"               # 只显示我的提交
          SHOW_LOC_CHART: "false"    
          SHOW_LANGUAGE_PER_REPO: "True"
          
          # 其他设置
          IGNORED_REPOS: ""                  # 忽略的仓库，用逗号分隔
          LOCALE: "en"                       # 语言设置 (en/cn)
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"  # 提交信息
